package admin

import (
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"slices"
	"strings"
	"time"

	"github.com/gin-gonic/gin"
	log "github.com/sirupsen/logrus"

	"github.com/wjsoj/CPA-Claude/internal/config"
	"github.com/wjsoj/CPA-Claude/internal/statement"
	"github.com/wjsoj/cc-core/requestlog"
)

// The usage-statement endpoints let a token holder export what they actually
// spent over a date range, as a PDF they can file for reimbursement.
//
// Ownership is proved the same way /status/api/history proves it: the caller
// presents the full client token. The document carries only the masked form,
// so the exported file is safe to hand to a finance department.
//
// Every figure traces to a request-log row: the charge the wallet was debited,
// converted at one rate for the whole document — the deployment's USD→CNY rate
// at export time. The request log stores no rate of its own, so there is no
// historical rate to convert at and the same range exported after the market
// moves will total differently. The document defends itself by printing the
// rate it used, so any two copies can be reconciled against each other.
//
// A statement can also be generated by target amount instead of by date range
// (TargetCNY on the request body). The caller names a yuan figure and the
// server walks backward from the newest request until spend reaches it, then
// renders whatever window that turned out to be — see the ByTarget doc on
// statement.Statement for how that stays honest rather than becoming "a total
// dialled to whatever a claimant needs": the derived range is captioned on
// the document rather than hidden, and every line on it is a charge that
// really happened. Real spend is the only ceiling; if the whole retained log
// cannot reach the target, the request is refused rather than served short.
//
// It is deliberately NOT capped at what the account paid via Alipay. That
// cap existed briefly and was removed: a wallet funded by operator credit
// reports an Alipay total of zero, so an account that had genuinely spent
// ¥1,543 could not export a statement of its own consumption. The document
// records what was consumed, which is true however the balance was funded,
// and says so in its own footer — the invoice flow is the other thing.

type statementBody struct {
	Token string `json:"token"`
	// From/To are inclusive day labels, YYYY-MM-DD, in the deployment's
	// display timezone. Empty defaults to the trailing 30 days. Mutually
	// exclusive with TargetCNY.
	From string `json:"from,omitempty"`
	To   string `json:"to,omitempty"`
	// TargetCNY switches the export from a named date range to a
	// target-amount scan: see the package doc above. Zero (the default)
	// keeps the ordinary From/To behaviour. Rejected if From or To is also
	// set — mixing the two would leave it ambiguous which the caller meant.
	TargetCNY float64 `json:"target_cny,omitempty"`
}

// statementModelRow mirrors statement.ModelRow for the JSON preview.
type statementModelRow struct {
	Model     string  `json:"model"`
	Requests  int64   `json:"requests"`
	BilledCNY float64 `json:"billed_cny"`
}

// statementPreview is what the export dialog renders before the user commits
// to a download: the real spend for the chosen range, the token's running
// total, and the rate behind both CNY figures.
type statementPreview struct {
	From     string `json:"from"`
	To       string `json:"to"`
	Timezone string `json:"timezone"`

	Requests  int64   `json:"requests"`
	BilledCNY float64 `json:"billed_cny"`
	// UnitemisedCNY is ledger-confirmed spend with no request-log row behind
	// it; ChargedCNY is the ledger's own total for the range. Both zero when
	// the two agree or no ledger figure was available.
	UnitemisedCNY float64 `json:"unitemised_cny,omitempty"`
	ChargedCNY    float64 `json:"charged_cny,omitempty"`

	LifetimeRequests  int64   `json:"lifetime_requests"`
	LifetimeBilledCNY float64 `json:"lifetime_billed_cny"`
	LifetimeDays      int     `json:"lifetime_days"`

	// ByTarget and TargetCNY disclose when From/To were derived by scanning
	// backward for a target amount rather than named by the caller, so a
	// preview can never be mistaken for an ordinary date-range one even by a
	// client that ignores the flag.
	ByTarget  bool    `json:"by_target,omitempty"`
	TargetCNY float64 `json:"target_cny,omitempty"`
	// TotalPaidCNY is the token's total Alipay-paid CNY — the ceiling a
	// target amount must not exceed. Always populated when SaaS billing is
	// enabled (not only on target requests), so the export dialog can show
	// the ceiling before the user ever switches into target mode.
	TotalPaidCNY float64 `json:"total_paid_cny,omitempty"`

	// DetailLines is how many rows the PDF will itemise, and Truncated says
	// that is fewer than Requests. Shown in the dialog so a long range does
	// not surprise the user with an abridged document after the download.
	DetailLines int  `json:"detail_lines"`
	Truncated   bool `json:"truncated"`

	ByModel []statementModelRow `json:"by_model"`
}

func (h *Handler) handleStatementPreview(c *gin.Context) {
	s, ok := h.buildStatement(c, false)
	if !ok {
		return
	}
	rows := make([]statementModelRow, 0, len(s.ByModel))
	for _, m := range s.ByModel {
		rows = append(rows, statementModelRow{
			Model: m.Model, Requests: m.Requests, BilledCNY: m.BilledCNY,
		})
	}
	c.JSON(http.StatusOK, statementPreview{
		From: s.FromDay, To: s.ToDay, Timezone: s.TZName,
		Requests: s.Requests, BilledCNY: s.BilledCNY,
		UnitemisedCNY:     s.UnitemisedCNY,
		ChargedCNY:        s.ChargedCNY,
		LifetimeRequests:  s.LifetimeRequests,
		LifetimeBilledCNY: s.LifetimeBilledCNY,
		LifetimeDays:      s.LifetimeDays,
		ByTarget:          s.ByTarget,
		TargetCNY:         s.TargetCNY,
		TotalPaidCNY:      s.TotalPaidCNY,
		DetailLines:       len(s.Lines), Truncated: s.LinesTruncated,
		ByModel: rows,
	})
}

func (h *Handler) handleStatementPDF(c *gin.Context) {
	s, ok := h.buildStatement(c, true)
	if !ok {
		return
	}
	buf, err := statement.Render(s)
	if err != nil {
		c.AbortWithStatusJSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}
	name := fmt.Sprintf("usage-statement-%s_%s.pdf", s.FromDay, s.ToDay)
	if s.ByTarget {
		name = fmt.Sprintf("usage-statement-target-%s_%s.pdf", s.FromDay, s.ToDay)
	}
	// Both filename forms: the bare one for clients that only read the first,
	// and RFC 5987 so a non-ASCII deployment name would survive if one is ever
	// folded in here.
	c.Header("Content-Disposition", fmt.Sprintf(
		`attachment; filename="%s"; filename*=UTF-8''%s`, name, url.PathEscape(name)))
	c.Header("Cache-Control", "no-store")
	c.Data(http.StatusOK, "application/pdf", buf)
}

// buildStatement validates the request, reads the log and assembles the
// document. withLines controls whether the itemised rows are collected — the
// preview needs only the totals, and a range covering tens of thousands of
// requests should not allocate all of them just to display three numbers.
//
// The two modes read the log in fundamentally different ways, and that is the
// point of the split below:
//
//   - A date range is answered from the pre-summed cube. Every figure the
//     document totals — request count, range spend, the per-model table — is
//     an aggregate, and agg_cube already folds Record.BilledOrCost per row
//     (see aggSelect in cc-core), so grouping it is exactly equal to summing
//     the rows by hand. Rows are then materialised only if the document is
//     going to print them, and only as many as it can print.
//   - A target amount has to walk the rows: where the window starts is what
//     the mode is trying to find out, and no aggregate can answer that.
//
// It writes the error response itself and reports ok=false when it does.
func (h *Handler) buildStatement(c *gin.Context, withLines bool) (*statement.Statement, bool) {
	if h.cfg.LogDir == "" {
		c.AbortWithStatusJSON(http.StatusServiceUnavailable, gin.H{"error": "log_dir not configured"})
		return nil, false
	}
	var body statementBody
	if err := c.ShouldBindJSON(&body); err != nil {
		c.AbortWithStatusJSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return nil, false
	}
	tok := strings.TrimSpace(body.Token)
	if tok == "" {
		c.AbortWithStatusJSON(http.StatusBadRequest, gin.H{"error": "token required"})
		return nil, false
	}
	entry, ok := h.tokens.Lookup(tok)
	if !ok {
		// Same non-disclosure as /query and /history: never reveal whether an
		// unknown token was deleted or never existed.
		c.AbortWithStatusJSON(http.StatusNotFound, gin.H{"error": "token not found"})
		return nil, false
	}
	masked := maskToken(tok)

	byTarget := body.TargetCNY > 0
	if byTarget && (strings.TrimSpace(body.From) != "" || strings.TrimSpace(body.To) != "") {
		c.AbortWithStatusJSON(http.StatusBadRequest,
			gin.H{"error": "target_cny 不能与 from/to 同时指定"})
		return nil, false
	}
	if body.TargetCNY < 0 {
		c.AbortWithStatusJSON(http.StatusBadRequest, gin.H{"error": "target_cny 不能为负数"})
		return nil, false
	}

	loc := requestlog.BucketLocation()

	// A target amount is bounded by what the account actually spent, and by
	// nothing else.
	//
	// It used to also be capped at the token's Alipay-paid total, on the theory
	// that nobody should be able to name a figure larger than money that
	// changed hands. That guard turned out to be both redundant and wrong.
	// Redundant because every line on the document is a charge that really
	// happened: statementRangeForTarget refuses outright when the retained log
	// cannot reach the target, so the spend itself is already a hard ceiling
	// and no amount of asking can conjure a row. Wrong because a wallet funded
	// by operator credit rather than by Alipay reported a ceiling of zero, so
	// an account that had genuinely spent ¥1,543 could not export a ¥1,500
	// statement of its own real consumption.
	//
	// The document is a consumption record, not a receipt — its own footnote
	// says so and points at the invoice flow for the other thing. What it
	// asserts is "these requests happened and cost this much", which is true
	// however the balance behind them was funded.
	var totalPaidCNY float64
	if h.wallets != nil {
		// Still surfaced to the dialog as context, just no longer a gate.
		// Failure is not fatal to the statement itself.
		if v, err := h.wallets.TotalPaidCNY(c.Request.Context(), tok); err == nil {
			totalPaidCNY = v
		}
	}

	var fromDay, toDay string
	var start, end time.Time
	if !byTarget {
		var err error
		fromDay, toDay, start, end, err = statementRange(body.From, body.To, loc)
		if err != nil {
			c.AbortWithStatusJSON(http.StatusBadRequest, gin.H{"error": err.Error()})
			return nil, false
		}
	}

	retention := h.cfg.LogRetentionDays
	if retention <= 0 {
		retention = 90
	}
	var lifetimeRequests int64
	var lifetimeUSD float64
	// The token is part of the filter. This used to issue a filter deliberately
	// identical to handleStatusQuery's — fleet-wide, capped at 200k rows — so
	// the two could share a cache entry, and then drop every row belonging to
	// somebody else. On a relay doing ~33k requests a day that cap reaches back
	// six days, so a token with 165k requests over three weeks had 20% of its
	// spend itemised and the rest silently invisible: a statement that read as
	// complete while understating what the account actually spent. Sharing a
	// scan with another endpoint is not worth a wrong number on a document
	// someone files for reimbursement.
	//
	// Every filter below states its window in day labels, never From/To
	// instants: a label is what agg_cube is keyed on, so the aggregates come
	// off the pre-aggregated cube while the itemised rows come off
	// idx_req_ct(client_token, ts DESC, id DESC). A timestamp pair would look
	// equivalent and quietly force both onto a row-by-row scan — and if both
	// are supplied the timestamp wins and the label is discarded.
	fromDayRetention := time.Now().In(loc).AddDate(0, 0, -(retention - 1)).Format("2006-01-02")

	// The running total is an aggregate, so it is read as one: a cube-only
	// query materialises no rows at all, whatever the account's volume.
	if lt, lerr := h.cachedQueryShared(requestlog.Filter{
		Dir:         h.cfg.LogDir,
		ClientToken: masked,
		FromDay:     fromDayRetention,
		Limit:       1,
	}, statusCacheTTL); lerr == nil {
		lifetimeRequests = lt.Summary.Count
		lifetimeUSD = lt.Summary.BilledUSD
	} else {
		log.Warnf("statement: lifetime rollup failed for %s: %v", masked, lerr)
	}

	rate := h.statementRate()

	// targetEntries is the row-by-row scan only a target-amount export needs:
	// the whole retained window, because where the window starts is precisely
	// what the mode is looking for. A date range never gets here — it is
	// answered from the cube below.
	var targetEntries []requestlog.Record
	if byTarget {
		res, err := h.cachedQueryShared(requestlog.Filter{
			Dir:         h.cfg.LogDir,
			ClientToken: masked,
			FromDay:     fromDayRetention,
			Limit:       statementMaxRows,
		}, statementScanCacheTTL)
		if err != nil {
			c.AbortWithStatusJSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
			return nil, false
		}
		// Summary.Count is the true number of matching rows; Entries is what
		// the cap let through. Locating the window from a truncated scan would
		// place the start too late and print a total short of the target, so
		// refuse — and point at the one mode that has no such ceiling.
		if res.Summary.Count > int64(len(res.Entries)) {
			log.Warnf("statement: %s matched %d rows since %s but the target scan capped at %d — refused",
				masked, res.Summary.Count, fromDayRetention, statementMaxRows)
			c.AbortWithStatusJSON(http.StatusRequestEntityTooLarge, gin.H{"error": fmt.Sprintf(
				"该令牌在留存窗口内有 %d 条记录，超过按目标金额生成的处理上限 %d 条，请改用日期区间导出",
				res.Summary.Count, statementMaxRows)})
			return nil, false
		}
		targetEntries = res.Entries

		var achievedCNY float64
		var terr error
		start, end, achievedCNY, terr = statementRangeForTarget(res.Entries, masked, body.TargetCNY, rate, time.Now())
		if terr != nil {
			if errors.Is(terr, errStatementTargetUnreachable) {
				c.AbortWithStatusJSON(http.StatusBadRequest, gin.H{"error": fmt.Sprintf(
					"该账户在可查询的日志留存窗口内合计消费 ¥%.2f，不足以生成 ¥%.2f 的账单",
					achievedCNY, body.TargetCNY)})
				return nil, false
			}
			c.AbortWithStatusJSON(http.StatusInternalServerError, gin.H{"error": terr.Error()})
			return nil, false
		}
		fromDay = start.In(loc).Format("2006-01-02")
		toDay = end.In(loc).Format("2006-01-02")
	}

	s := &statement.Statement{
		TokenMasked:  masked,
		TokenName:    entry.Name,
		Group:        entry.Group,
		FromDay:      fromDay,
		ToDay:        toDay,
		TZName:       loc.String(),
		CNYPerUSD:    rate,
		GeneratedAt:  time.Now().In(loc),
		LifetimeDays: retention,
		ByTarget:     byTarget,
		TargetCNY:    body.TargetCNY,
		TotalPaidCNY: totalPaidCNY,
	}
	if byTarget {
		// The exact boundaries, not just their day labels: a target-derived
		// window opens partway through a day and the document has to say so.
		s.RangeStart, s.RangeEnd = start.In(loc), end.In(loc)
	}
	if h.wallets != nil {
		if w, err := h.wallets.GetWallet(c.Request.Context(), tok); err == nil {
			if g, err := h.wallets.GetGroup(c.Request.Context(), w.GroupID); err == nil && g.Name != "" {
				s.Group = g.Name
			}
		}
	}

	// rangeUSD is the range total in the ledger's own currency, which is what
	// the reconciliation below compares against — the ledger is USD-denominated
	// and converting it separately would compound the same rounding twice.
	var lines []statement.Line
	var rangeUSD float64

	if byTarget {
		// Entries arrive newest-first and the walk keeps that order, so when
		// MaxDetailLines bites the rows kept are the newest of the window
		// rather than the oldest. That matters in practice: rows written before
		// 2026-08-09 were synthesised from wallet transactions and carry no
		// token counts at all, so a long window truncated from the old end
		// prints three thousand rows of blanks. The slice is flipped to
		// chronological order afterwards — the document still reads forward.
		for _, rec := range targetEntries {
			if rec.TS.Before(start) || !rec.TS.Before(end) {
				continue
			}
			// BilledOrCost, not BilledUSD: until cc-core v0.8.61 one fork wrote
			// the charged amount into CostUSD and left BilledUSD unset, and a
			// 90-day retention means both conventions coexist in one directory.
			usd := rec.BilledOrCost()
			cny := usd * rate
			// Observe carries the range totals and the per-model rollup for
			// every in-range row, not just the retained ones, so the model
			// table sums to BilledCNY on a truncated statement and is non-empty
			// on the preview.
			s.Observe(rec.Model, cny)
			rangeUSD += usd
			if withLines && len(lines) < statement.MaxDetailLines {
				lines = append(lines, statementLine(rec, loc, cny))
			}
		}
		slices.Reverse(lines)
	} else {
		// Day labels, and a Limit of 1 so nothing is materialised: this filter
		// is cube-eligible, so Summary and ByModel come off ~10k pre-summed
		// rows whatever the account's volume. Timestamps here would look
		// equivalent and silently drop the query back onto a row-by-row scan.
		agg, aerr := h.cachedQueryShared(requestlog.Filter{
			Dir:         h.cfg.LogDir,
			ClientToken: masked,
			FromDay:     fromDay,
			ToDay:       toDay,
			Limit:       1,
		}, statusCacheTTL)
		if aerr != nil {
			c.AbortWithStatusJSON(http.StatusInternalServerError, gin.H{"error": aerr.Error()})
			return nil, false
		}
		rangeUSD = agg.Summary.BilledUSD
		rows := make([]statement.ModelRow, 0, len(agg.ByModel))
		for model, a := range agg.ByModel {
			rows = append(rows, statement.ModelRow{
				// An empty model name is relabelled by SetRangeTotals, the
				// same way Observe relabels it on the other path.
				Model: model, Requests: a.Count, BilledCNY: a.BilledUSD * rate,
			})
		}
		s.SetRangeTotals(agg.Summary.Count, agg.Summary.BilledUSD*rate, rows)

		// Only now, and only as many rows as the document can print. This used
		// to pull the whole range — up to statementMaxRows — and refuse the
		// export above the cap, which is how an account big enough to trip it
		// could never export anything at all. The totals no longer depend on
		// materialising anything, so there is nothing left to refuse.
		if withLines {
			det, derr := h.cachedQueryShared(requestlog.Filter{
				Dir:         h.cfg.LogDir,
				ClientToken: masked,
				FromDay:     fromDay,
				ToDay:       toDay,
				Limit:       statement.MaxDetailLines,
			}, statementScanCacheTTL)
			if derr != nil {
				c.AbortWithStatusJSON(http.StatusInternalServerError, gin.H{"error": derr.Error()})
				return nil, false
			}
			// Newest-first, so this is the newest MaxDetailLines of the range;
			// reversed below into the chronological order the page reads in.
			for _, rec := range det.Entries {
				lines = append(lines, statementLine(rec, loc, rec.BilledOrCost()*rate))
			}
			slices.Reverse(lines)
		}
	}
	s.Lines = lines
	s.LinesTruncated = withLines && s.Requests > int64(len(lines))
	s.Rollup()

	// The running total is context, not a claim: it says roughly what the token
	// has spent over the retained window, beside the range the document is
	// actually about. It comes off the cube, which carries USD only, so it is
	// converted at the same rate as everything else on the page — the figure is
	// directly comparable with the range total for that reason.
	//
	// This used to derive a rate from the itemised range (BilledCNY / rangeUSD)
	// because rows could each carry their own. With one rate for the whole
	// document that division is the identity, so it is gone rather than left in
	// as a calculation that no longer explains anything.
	s.LifetimeRequests = lifetimeRequests
	s.LifetimeBilledCNY = lifetimeUSD * rate

	h.reconcileAgainstLedger(c, tok, s, rangeUSD, start, end, rate)

	// The preview reports the row count the PDF will carry, so it has to apply
	// the same cap without having collected the rows.
	if !withLines {
		n := s.Requests
		if n > statement.MaxDetailLines {
			n = statement.MaxDetailLines
			s.LinesTruncated = true
		}
		s.Lines = make([]statement.Line, n)
	}
	return s, true
}

// statementLine renders one request-log row as a printable line.
//
// There is deliberately no cache-write count: OpenAI reports cached_tokens (a
// read) and has no cache-creation concept at all, and this relay's traffic is
// almost entirely OpenAI, so the column would be a permanent zero.
func statementLine(rec requestlog.Record, loc *time.Location, cny float64) statement.Line {
	return statement.Line{
		TS: rec.TS.In(loc), Provider: rec.Provider, Model: rec.Model,
		Input: rec.Input, Output: rec.Output, CacheRead: rec.CacheRead,
		BilledCNY: cny, Status: rec.Status,
	}
}

// reconcileAgainstLedger compares the itemised total against what the wallet
// was actually debited over the same window, and records any shortfall.
//
// The two records are produced independently — the debit is a transaction, the
// itemised row a separate append to the request log — so the log can lose a
// line the ledger still holds. Surfacing the difference as its own labelled
// figure lets the document total match the money without fabricating the
// requests behind it, which is the whole point: the gap is reported, never
// distributed across invented line items.
//
// The gap converts at the statement's own rate, the same one every other figure
// on the page used — it is a slice of the same USD ledger, so converting it any
// other way would make the three closing lines fail to add up.
//
// Failure is silent by design: reconciliation is an enrichment, and a statement
// that refuses to render because SQLite was briefly busy is worse than one that
// simply omits the extra line.
func (h *Handler) reconcileAgainstLedger(
	c *gin.Context, tok string, s *statement.Statement,
	rangeUSD float64, start, end time.Time, rate float64,
) {
	if h.wallets == nil {
		return
	}
	chargedUSD, err := h.wallets.ChargedUSDBetween(c.Request.Context(), tok, start, end)
	if err != nil {
		log.Warnf("statement: ledger reconciliation failed for %s: %v", maskToken(tok), err)
		return
	}
	if chargedUSD <= 0 {
		return
	}

	if rate <= 0 {
		return
	}
	s.ChargedCNY = chargedUSD * rate

	// Only a shortfall is meaningful. The log accounting for more than the
	// ledger means something else (an unbilled attempt row, a refund) and is
	// not evidence of a missing charge, so it is never shown as one.
	//
	// The gap also has to survive being written down: the threshold is in USD,
	// but the figure is printed in yuan to two decimals, so a gap of a few
	// hundredths of a cent cleared the USD floor and then rendered as a line
	// reading "未能明细化的消费 ¥0.00" — an entry asserting that nothing is
	// missing, which is worse than no entry at all. Half a fen is where a
	// discrepancy becomes something a reader can actually see.
	gap := chargedUSD - rangeUSD
	if gap > ledgerGapEpsilonUSD && gap*rate >= unitemisedFloorCNY {
		s.UnitemisedCNY = gap * rate
	} else {
		// Within noise: present the ledger total as exactly the itemised one so
		// the document does not show a one-fen discrepancy it cannot explain.
		s.ChargedCNY = s.BilledCNY
	}
}

// defaultStatementCNYPerUSD is the last resort in statementRate's chain. It is
// config's own default rather than a second copy of the literal: a deployment
// that never configured an exchange rate must export the same figures the
// wallet quotes, and two literals could only guarantee that by being watched.
const defaultStatementCNYPerUSD = config.DefaultCNYPerUSD

// statementRate is the single USD→CNY rate the whole document converts at.
//
// It must never return zero. Every yuan figure on the page is one
// multiplication by this number, so a zero renders an entire statement as ¥0.00
// — a document that is not merely unhelpful but actively wrong, and wrong in
// the direction a reader is least likely to question. There used to be an
// accidental safety net here: rows carried their own settle-time rate and only
// the legacy ones needed a fallback, so a non-SaaS deployment with no exchange
// refresher still totalled correctly. That net is gone, hence the explicit
// chain: live rate → configured fallback → compiled-in default.
func (h *Handler) statementRate() float64 {
	if h.billing != nil && h.billing.Rate != nil {
		if v := h.billing.Rate.CNYPerUSD(); v > 0 {
			return v
		}
	}
	if h.cfg != nil && h.cfg.SaaS.Exchange.FallbackCNYPerUSD > 0 {
		return h.cfg.SaaS.Exchange.FallbackCNYPerUSD
	}
	return defaultStatementCNYPerUSD
}

// ledgerGapEpsilonUSD is the float-noise floor below which the itemised total
// and the ledger are treated as agreeing. Charges quantize to 1e-8, so anything
// under a hundredth of a cent is rounding, not a missing request.
const ledgerGapEpsilonUSD = 1e-4

// unitemisedFloorCNY is the smallest gap worth printing: half a fen, the point
// at which it stops rounding to ¥0.00 on the document.
const unitemisedFloorCNY = 0.005

// statementMaxRows bounds the one scan that still has to materialise rows: the
// target-amount mode's walk back through the retained window. Record is a wide
// struct, so this is the real memory ceiling of that export — roughly 300 bytes
// a row, ~150MB here — and crossing it refuses rather than truncates, because a
// window located from a truncated scan starts too late and prints a total short
// of the target it claims.
//
// It does not bound a date-range export any more. Those read their totals off
// the pre-summed cube and materialise at most MaxDetailLines rows, so there is
// no volume of traffic that can put one out of reach.
//
// It is a per-token bound, not the fleet-wide one it replaced, so it stands
// for a genuinely enormous single account rather than six days of everybody.
// A var, not a const, so a test can lower it: the failure it guards against
// only appears once the cap is crossed, and a test that had to write half a
// million rows to reach it would never be written.
//
// Process-global, so the tests that lower it must not call t.Parallel(). If
// this package ever gains parallel tests, move it onto Handler instead of
// making the tests work around it.
var statementMaxRows = 500000

// statementScanCacheTTL is deliberately much shorter than statusCacheTTL.
//
// The row scans behind an export are the largest objects this process caches —
// up to statementMaxRows materialised Records for a target-amount walk — and
// unlike the polled status endpoints they have exactly one reuse worth having:
// the preview the dialog draws and the PDF the user then downloads, seconds
// apart. Holding them for a minute per token bought nothing and let a handful
// of large accounts pin hundreds of megabytes at once on a host that already
// runs under earlyoom.
//
// The aggregates a date-range export reads are cached at statusCacheTTL
// instead: they are a handful of numbers, and that is the TTL handleStatusQuery
// uses, so the export rides whatever entry the panel already warmed.
const statementScanCacheTTL = 10 * time.Second

// statementDefaultDays is the range the dialog opens on when the caller sends
// none — long enough to cover a typical monthly reimbursement cycle.
const statementDefaultDays = 30

// statementMaxRangeDays bounds the scan a single export can ask for. The log
// itself is retention-bounded, so this only guards against a caller naming a
// range far wider than the data behind it.
const statementMaxRangeDays = 400

// errStatementTargetUnreachable means the whole retained log window, summed
// end to end, still falls short of the requested target — there is no window
// this token's spend could possibly fill it with.
var errStatementTargetUnreachable = errors.New("target amount exceeds total spend in the retained log window")

// statementRangeForTarget locates the range for a target-amount statement.
//
// entries is the newest-first slice cachedQueryShared returns (the same one
// buildStatement's main loop reads chronologically by walking it backward).
// This walks it forward instead — from newest to oldest, exactly the order
// it already arrives in — accumulating masked's own rows' BilledCNY until the
// running total reaches targetCNY, and returns that row's timestamp as start.
//
// It never splits a row to land exactly on the target: accumulation stops at
// the first row that pushes the total to or past it, so the achieved amount
// is always >= targetCNY (or the call fails outright). end is always now —
// the window runs from the located start up through the moment of generation,
// which real conversation activity may or may not have filled right up to.
//
// achievedCNY is returned even on failure (the full window's total), because
// the caller uses it to explain by how much the request fell short.
func statementRangeForTarget(entries []requestlog.Record, masked string, targetCNY, rate float64, now time.Time) (start, end time.Time, achievedCNY float64, err error) {
	end = now
	for _, rec := range entries {
		// Redundant against the caller, which now filters by token in the
		// query, but kept because this is a pure helper with its own unit
		// tests that feed it mixed slices — it should not silently depend on
		// having been handed a pre-filtered one.
		if rec.ClientToken != masked {
			continue
		}
		// Skip anything the statement itself will not carry. buildStatement's
		// main loop bounds rows at [start, end), so a row at or after end can
		// never appear on the document — counting it here would pick a start
		// that leaves the printed total short of the target, which is the one
		// thing a target-amount statement must never do. Rows dated ahead of
		// the generating clock are not hypothetical: a log written across hosts
		// only needs one of them stepping its clock forward.
		if !rec.TS.Before(end) {
			continue
		}
		// The same conversion buildStatement's own loop performs, so the window
		// this picks and the total that gets printed cannot disagree.
		achievedCNY += rec.BilledOrCost() * rate
		start = rec.TS
		if achievedCNY >= targetCNY {
			return start, end, achievedCNY, nil
		}
	}
	return time.Time{}, time.Time{}, achievedCNY, errStatementTargetUnreachable
}

// statementRange resolves the inclusive day labels into the half-open instant
// window [start, end) that rows are compared against.
//
// The labels are interpreted in loc, the display zone, because that is the zone
// the request log buckets days in — reading them as UTC would shift every
// boundary by the offset and silently move requests between statements.
func statementRange(from, to string, loc *time.Location) (fromDay, toDay string, start, end time.Time, err error) {
	const layout = "2006-01-02"
	today := time.Now().In(loc)

	parse := func(s, field string) (time.Time, error) {
		s = strings.TrimSpace(s)
		if s == "" {
			return time.Time{}, nil
		}
		d, perr := time.ParseInLocation(layout, s, loc)
		if perr != nil {
			return time.Time{}, fmt.Errorf("%s must be YYYY-MM-DD", field)
		}
		return d, nil
	}

	f, err := parse(from, "from")
	if err != nil {
		return "", "", time.Time{}, time.Time{}, err
	}
	t, err := parse(to, "to")
	if err != nil {
		return "", "", time.Time{}, time.Time{}, err
	}

	if t.IsZero() {
		t = time.Date(today.Year(), today.Month(), today.Day(), 0, 0, 0, 0, loc)
	}
	if f.IsZero() {
		f = t.AddDate(0, 0, -(statementDefaultDays - 1))
	}
	if t.Before(f) {
		f, t = t, f
	}
	if days := int(t.Sub(f).Hours()/24) + 1; days > statementMaxRangeDays {
		return "", "", time.Time{}, time.Time{},
			fmt.Errorf("range too wide: %d days (max %d)", days, statementMaxRangeDays)
	}

	// end is exclusive at the start of the day after `to`, which is what makes
	// the range include everything that happened on `to` itself.
	return f.Format(layout), t.Format(layout), f, t.AddDate(0, 0, 1), nil
}
