package admin

import (
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/gin-gonic/gin"
	log "github.com/sirupsen/logrus"

	"github.com/wjsoj/CPA-Claude/internal/statement"
	"github.com/wjsoj/cc-core/requestlog"
)

// The usage-statement endpoints let a token holder export what they actually
// spent over a date range, as a PDF they can file for reimbursement.
//
// Ownership is proved the same way /status/api/history proves it: the caller
// presents the full client token. The document carries only the masked form,
// so the exported file is safe to hand to a finance department.
//
// Every figure traces to a request-log row: the charge the wallet was debited,
// converted at the USD→CNY rate that row settled at (Record.CNYPerUSD). Since
// the rate is stored per row rather than looked up when the PDF is drawn, the
// same range exported months apart totals identically — which is what makes
// the document worth anything as evidence.
//
// A statement can also be generated by target amount instead of by date range
// (TargetCNY on the request body). The caller names a yuan figure and the
// server walks backward from the newest request until spend reaches it, then
// renders whatever window that turned out to be — see the ByTarget doc on
// statement.Statement for how that stays honest rather than becoming "a total
// dialled to whatever a claimant needs": the derived range is captioned on
// the document rather than hidden, and the target is capped at the account's
// real Alipay-paid total (TotalPaidCNY below) so nobody can manufacture a
// bigger figure than they ever paid for. If even the whole retained log
// doesn't reach the target, the request is refused rather than served short.

type statementBody struct {
	Token string `json:"token"`
	// From/To are inclusive day labels, YYYY-MM-DD, in the deployment's
	// display timezone. Empty defaults to the trailing 30 days. Mutually
	// exclusive with TargetCNY.
	From string `json:"from,omitempty"`
	To   string `json:"to,omitempty"`
	// TargetCNY switches the export from a named date range to a
	// target-amount scan: see the package doc above. Zero (the default)
	// keeps the ordinary From/To behaviour. Rejected if From or To is also
	// set — mixing the two would leave it ambiguous which the caller meant.
	TargetCNY float64 `json:"target_cny,omitempty"`
}

// statementModelRow mirrors statement.ModelRow for the JSON preview.
type statementModelRow struct {
	Model     string  `json:"model"`
	Requests  int64   `json:"requests"`
	BilledCNY float64 `json:"billed_cny"`
}

// statementPreview is what the export dialog renders before the user commits
// to a download: the real spend for the chosen range, the token's running
// total, and the rate behind both CNY figures.
type statementPreview struct {
	From     string `json:"from"`
	To       string `json:"to"`
	Timezone string `json:"timezone"`

	Requests  int64   `json:"requests"`
	BilledCNY float64 `json:"billed_cny"`
	// UnitemisedCNY is ledger-confirmed spend with no request-log row behind
	// it; ChargedCNY is the ledger's own total for the range. Both zero when
	// the two agree or no ledger figure was available.
	UnitemisedCNY float64 `json:"unitemised_cny,omitempty"`
	ChargedCNY    float64 `json:"charged_cny,omitempty"`

	LifetimeRequests  int64   `json:"lifetime_requests"`
	LifetimeBilledCNY float64 `json:"lifetime_billed_cny"`
	LifetimeDays      int     `json:"lifetime_days"`

	// ByTarget and TargetCNY disclose when From/To were derived by scanning
	// backward for a target amount rather than named by the caller, so a
	// preview can never be mistaken for an ordinary date-range one even by a
	// client that ignores the flag.
	ByTarget  bool    `json:"by_target,omitempty"`
	TargetCNY float64 `json:"target_cny,omitempty"`
	// TotalPaidCNY is the token's total Alipay-paid CNY — the ceiling a
	// target amount must not exceed. Always populated when SaaS billing is
	// enabled (not only on target requests), so the export dialog can show
	// the ceiling before the user ever switches into target mode.
	TotalPaidCNY float64 `json:"total_paid_cny,omitempty"`

	// UnratedRequests counts in-range rows predating per-row rate capture,
	// whose yuan figure had to be derived at the current rate. Surfaced so the
	// dialog can carry the same caveat the document does.
	UnratedRequests int64 `json:"unrated_requests,omitempty"`

	// DetailLines is how many rows the PDF will itemise, and Truncated says
	// that is fewer than Requests. Shown in the dialog so a long range does
	// not surprise the user with an abridged document after the download.
	DetailLines int  `json:"detail_lines"`
	Truncated   bool `json:"truncated"`

	ByModel []statementModelRow `json:"by_model"`
}

func (h *Handler) handleStatementPreview(c *gin.Context) {
	s, ok := h.buildStatement(c, false)
	if !ok {
		return
	}
	rows := make([]statementModelRow, 0, len(s.ByModel))
	for _, m := range s.ByModel {
		rows = append(rows, statementModelRow{
			Model: m.Model, Requests: m.Requests, BilledCNY: m.BilledCNY,
		})
	}
	c.JSON(http.StatusOK, statementPreview{
		From: s.FromDay, To: s.ToDay, Timezone: s.TZName,
		Requests: s.Requests, BilledCNY: s.BilledCNY,
		UnitemisedCNY:     s.UnitemisedCNY,
		ChargedCNY:        s.ChargedCNY,
		LifetimeRequests:  s.LifetimeRequests,
		LifetimeBilledCNY: s.LifetimeBilledCNY,
		LifetimeDays:      s.LifetimeDays,
		ByTarget:          s.ByTarget,
		TargetCNY:         s.TargetCNY,
		TotalPaidCNY:      s.TotalPaidCNY,
		UnratedRequests:   s.UnratedRequests,
		DetailLines:       len(s.Lines), Truncated: s.LinesTruncated,
		ByModel: rows,
	})
}

func (h *Handler) handleStatementPDF(c *gin.Context) {
	s, ok := h.buildStatement(c, true)
	if !ok {
		return
	}
	buf, err := statement.Render(s)
	if err != nil {
		c.AbortWithStatusJSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}
	name := fmt.Sprintf("usage-statement-%s_%s.pdf", s.FromDay, s.ToDay)
	if s.ByTarget {
		name = fmt.Sprintf("usage-statement-target-%s_%s.pdf", s.FromDay, s.ToDay)
	}
	// Both filename forms: the bare one for clients that only read the first,
	// and RFC 5987 so a non-ASCII deployment name would survive if one is ever
	// folded in here.
	c.Header("Content-Disposition", fmt.Sprintf(
		`attachment; filename="%s"; filename*=UTF-8''%s`, name, url.PathEscape(name)))
	c.Header("Cache-Control", "no-store")
	c.Data(http.StatusOK, "application/pdf", buf)
}

// buildStatement validates the request, scans the log once and assembles the
// document. withLines controls whether the itemised rows are collected — the
// preview needs only the totals, and a range covering tens of thousands of
// requests should not allocate all of them just to display three numbers.
//
// It writes the error response itself and reports ok=false when it does.
func (h *Handler) buildStatement(c *gin.Context, withLines bool) (*statement.Statement, bool) {
	if h.cfg.LogDir == "" {
		c.AbortWithStatusJSON(http.StatusServiceUnavailable, gin.H{"error": "log_dir not configured"})
		return nil, false
	}
	var body statementBody
	if err := c.ShouldBindJSON(&body); err != nil {
		c.AbortWithStatusJSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return nil, false
	}
	tok := strings.TrimSpace(body.Token)
	if tok == "" {
		c.AbortWithStatusJSON(http.StatusBadRequest, gin.H{"error": "token required"})
		return nil, false
	}
	entry, ok := h.tokens.Lookup(tok)
	if !ok {
		// Same non-disclosure as /query and /history: never reveal whether an
		// unknown token was deleted or never existed.
		c.AbortWithStatusJSON(http.StatusNotFound, gin.H{"error": "token not found"})
		return nil, false
	}
	masked := maskToken(tok)

	byTarget := body.TargetCNY > 0
	if byTarget && (strings.TrimSpace(body.From) != "" || strings.TrimSpace(body.To) != "") {
		c.AbortWithStatusJSON(http.StatusBadRequest,
			gin.H{"error": "target_cny 不能与 from/to 同时指定"})
		return nil, false
	}
	if body.TargetCNY < 0 {
		c.AbortWithStatusJSON(http.StatusBadRequest, gin.H{"error": "target_cny 不能为负数"})
		return nil, false
	}

	loc := requestlog.BucketLocation()

	// A target amount requires a real ceiling to check against — the token's
	// own Alipay-paid total — which requires SaaS billing. Checked before
	// anything else in target mode so a deployment with billing off gets a
	// clear reason rather than an "unreachable" error that blames the log.
	var totalPaidCNY float64
	if byTarget {
		if h.wallets == nil {
			c.AbortWithStatusJSON(http.StatusBadRequest,
				gin.H{"error": "该部署未启用钱包计费，无法按目标金额生成对账单"})
			return nil, false
		}
		var err error
		totalPaidCNY, err = h.wallets.TotalPaidCNY(c.Request.Context(), tok)
		if err != nil {
			c.AbortWithStatusJSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
			return nil, false
		}
		// Compared with a half-fen tolerance rather than exactly. The ceiling is
		// a float sum over the order rows, and claiming the full paid amount is
		// this feature's most obvious use — the dialog shows the total rounded to
		// two decimals and the user types that back. A sum that lands a few ulp
		// low (9.9+1+19.9 = 30.799999999999997, displayed ¥30.80) would then
		// refuse the request while quoting two identical figures at them.
		if body.TargetCNY > totalPaidCNY+targetCeilingEpsilonCNY {
			c.AbortWithStatusJSON(http.StatusBadRequest, gin.H{"error": fmt.Sprintf(
				"目标金额 ¥%.2f 超过该账户实付充值总额 ¥%.2f，无法生成", body.TargetCNY, totalPaidCNY)})
			return nil, false
		}
	} else if h.wallets != nil {
		// Not required for a date-range statement, but cheap and lets the
		// export dialog show the ceiling before the user ever switches into
		// target mode. Failure here is not fatal to the statement itself.
		if v, err := h.wallets.TotalPaidCNY(c.Request.Context(), tok); err == nil {
			totalPaidCNY = v
		}
	}

	var fromDay, toDay string
	var start, end time.Time
	if !byTarget {
		var err error
		fromDay, toDay, start, end, err = statementRange(body.From, body.To, loc)
		if err != nil {
			c.AbortWithStatusJSON(http.StatusBadRequest, gin.H{"error": err.Error()})
			return nil, false
		}
	}

	retention := h.cfg.LogRetentionDays
	if retention <= 0 {
		retention = 90
	}
	// One scan serves both windows. The filter is deliberately identical to
	// the one handleStatusQuery issues, so the statement rides that endpoint's
	// warm cache instead of forcing its own pass over the archive.
	res, err := h.cachedQueryShared(requestlog.Filter{
		Dir:   h.cfg.LogDir,
		From:  time.Now().UTC().Truncate(24*time.Hour).AddDate(0, 0, -(retention - 1)),
		Limit: 200000,
	}, statusCacheTTL)
	if err != nil {
		c.AbortWithStatusJSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return nil, false
	}

	// Fallback for rows written before per-row rate capture. Only those rows
	// use it; anything carrying its own rate converts at that one, so the bulk
	// of a statement stays reproducible even while legacy rows are in range.
	fallbackRate := 0.0
	if h.billing != nil && h.billing.Rate != nil {
		fallbackRate = h.billing.Rate.CNYPerUSD()
	}

	if byTarget {
		var achievedCNY float64
		start, end, achievedCNY, err = statementRangeForTarget(res.Entries, masked, body.TargetCNY, fallbackRate, time.Now())
		if err != nil {
			if errors.Is(err, errStatementTargetUnreachable) {
				c.AbortWithStatusJSON(http.StatusBadRequest, gin.H{"error": fmt.Sprintf(
					"该账户在可查询的日志留存窗口内合计消费 ¥%.2f，不足以生成 ¥%.2f 的账单",
					achievedCNY, body.TargetCNY)})
				return nil, false
			}
			c.AbortWithStatusJSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
			return nil, false
		}
		fromDay = start.In(loc).Format("2006-01-02")
		toDay = end.In(loc).Format("2006-01-02")
	}

	s := &statement.Statement{
		TokenMasked:  masked,
		TokenName:    entry.Name,
		Group:        entry.Group,
		FromDay:      fromDay,
		ToDay:        toDay,
		TZName:       loc.String(),
		GeneratedAt:  time.Now().In(loc),
		LifetimeDays: retention,
		ByTarget:     byTarget,
		TargetCNY:    body.TargetCNY,
		TotalPaidCNY: totalPaidCNY,
	}
	if byTarget {
		// The exact boundaries, not just their day labels: a target-derived
		// window opens partway through a day and the document has to say so.
		s.RangeStart, s.RangeEnd = start.In(loc), end.In(loc)
	}
	if h.wallets != nil {
		if w, err := h.wallets.GetWallet(c.Request.Context(), tok); err == nil {
			if g, err := h.wallets.GetGroup(c.Request.Context(), w.GroupID); err == nil && g.Name != "" {
				s.Group = g.Name
			}
		}
	}

	// Query returns entries newest-first; the statement reads chronologically,
	// so rows are appended in reverse.
	//
	// rangeUSD tracks the same rows in their ledger currency, purely so the
	// reconciliation below can compare like with like and derive the range's
	// own effective rate.
	var lines []statement.Line
	var rangeUSD float64
	for i := len(res.Entries) - 1; i >= 0; i-- {
		rec := res.Entries[i]
		if rec.ClientToken != masked {
			continue
		}
		// Each row converts at the rate it settled at. BilledCNY reports
		// ok=false for rows predating that column rather than converting at
		// zero, and those fall back to the current rate — tracked separately
		// so the document can disclose how many did.
		cny, rated := rec.BilledCNY()
		if !rated {
			// BilledOrCost, not BilledUSD: until cc-core v0.8.61 one fork wrote
			// the charged amount into CostUSD and left BilledUSD unset, and a
			// 90-day retention means both conventions coexist in one directory.
			cny = rec.BilledOrCost() * fallbackRate
		}

		s.LifetimeRequests++
		s.LifetimeBilledCNY += cny

		if rec.TS.Before(start) || !rec.TS.Before(end) {
			continue
		}
		// Observe carries the range totals and the per-model rollup for every
		// in-range row, not just the retained ones, so the model table sums to
		// BilledCNY on a truncated statement and is non-empty on the preview.
		s.Observe(rec.Model, cny, rated)
		rangeUSD += rec.BilledOrCost()
		if withLines && len(lines) < statement.MaxDetailLines {
			lines = append(lines, statement.Line{
				TS: rec.TS.In(loc), Provider: rec.Provider, Model: rec.Model,
				Input: rec.Input, Output: rec.Output,
				CacheRead: rec.CacheRead, CacheCreate: rec.CacheCreate,
				BilledCNY: cny, RateWasStored: rated, Status: rec.Status,
			})
		}
	}
	s.Lines = lines
	s.LinesTruncated = withLines && s.Requests > int64(len(lines))
	s.Rollup()
	h.reconcileAgainstLedger(c, tok, s, rangeUSD, start, end, fallbackRate)

	// The preview reports the row count the PDF will carry, so it has to apply
	// the same cap without having collected the rows.
	if !withLines {
		n := s.Requests
		if n > statement.MaxDetailLines {
			n = statement.MaxDetailLines
			s.LinesTruncated = true
		}
		s.Lines = make([]statement.Line, n)
	}
	return s, true
}

// reconcileAgainstLedger compares the itemised total against what the wallet
// was actually debited over the same window, and records any shortfall.
//
// The two records are produced independently — the debit is a transaction, the
// itemised row a separate append to the request log — so the log can lose a
// line the ledger still holds. Surfacing the difference as its own labelled
// figure lets the document total match the money without fabricating the
// requests behind it, which is the whole point: the gap is reported, never
// distributed across invented line items.
//
// The gap converts at the range's OWN effective rate (its yuan total over its
// USD total) rather than today's, so the figure stays reproducible for the same
// reason every other number here does. With nothing itemised to derive a rate
// from, it falls back to the current one.
//
// Failure is silent by design: reconciliation is an enrichment, and a statement
// that refuses to render because SQLite was briefly busy is worse than one that
// simply omits the extra line.
func (h *Handler) reconcileAgainstLedger(
	c *gin.Context, tok string, s *statement.Statement,
	rangeUSD float64, start, end time.Time, fallbackRate float64,
) {
	if h.wallets == nil {
		return
	}
	chargedUSD, err := h.wallets.ChargedUSDBetween(c.Request.Context(), tok, start, end)
	if err != nil {
		log.Warnf("statement: ledger reconciliation failed for %s: %v", maskToken(tok), err)
		return
	}
	if chargedUSD <= 0 {
		return
	}

	rate := fallbackRate
	if rangeUSD > 0 && s.BilledCNY > 0 {
		rate = s.BilledCNY / rangeUSD
	}
	if rate <= 0 {
		return
	}
	s.ChargedCNY = chargedUSD * rate

	// Only a shortfall is meaningful. The log accounting for more than the
	// ledger means something else (an unbilled attempt row, a refund) and is
	// not evidence of a missing charge, so it is never shown as one.
	if gap := chargedUSD - rangeUSD; gap > ledgerGapEpsilonUSD {
		s.UnitemisedCNY = gap * rate
	} else {
		// Within noise: present the ledger total as exactly the itemised one so
		// the document does not show a one-fen discrepancy it cannot explain.
		s.ChargedCNY = s.BilledCNY
	}
}

// ledgerGapEpsilonUSD is the float-noise floor below which the itemised total
// and the ledger are treated as agreeing. Charges quantize to 1e-8, so anything
// under a hundredth of a cent is rounding, not a missing request.
const ledgerGapEpsilonUSD = 1e-4

// targetCeilingEpsilonCNY is the tolerance on the target-vs-paid-total check:
// half a fen, the smallest amount anyone can actually pay. Wide enough to
// absorb float error in the summed order rows, far too narrow to let a target
// exceed the money that changed hands by anything expressible in currency.
const targetCeilingEpsilonCNY = 0.005

// statementDefaultDays is the range the dialog opens on when the caller sends
// none — long enough to cover a typical monthly reimbursement cycle.
const statementDefaultDays = 30

// statementMaxRangeDays bounds the scan a single export can ask for. The log
// itself is retention-bounded, so this only guards against a caller naming a
// range far wider than the data behind it.
const statementMaxRangeDays = 400

// errStatementTargetUnreachable means the whole retained log window, summed
// end to end, still falls short of the requested target — there is no window
// this token's spend could possibly fill it with.
var errStatementTargetUnreachable = errors.New("target amount exceeds total spend in the retained log window")

// statementRangeForTarget locates the range for a target-amount statement.
//
// entries is the newest-first slice cachedQueryShared returns (the same one
// buildStatement's main loop reads chronologically by walking it backward).
// This walks it forward instead — from newest to oldest, exactly the order
// it already arrives in — accumulating masked's own rows' BilledCNY until the
// running total reaches targetCNY, and returns that row's timestamp as start.
//
// It never splits a row to land exactly on the target: accumulation stops at
// the first row that pushes the total to or past it, so the achieved amount
// is always >= targetCNY (or the call fails outright). end is always now —
// the window runs from the located start up through the moment of generation,
// which real conversation activity may or may not have filled right up to.
//
// achievedCNY is returned even on failure (the full window's total), because
// the caller uses it to explain by how much the request fell short.
func statementRangeForTarget(entries []requestlog.Record, masked string, targetCNY, fallbackRate float64, now time.Time) (start, end time.Time, achievedCNY float64, err error) {
	end = now
	for _, rec := range entries {
		if rec.ClientToken != masked {
			continue
		}
		// Skip anything the statement itself will not carry. buildStatement's
		// main loop bounds rows at [start, end), so a row at or after end can
		// never appear on the document — counting it here would pick a start
		// that leaves the printed total short of the target, which is the one
		// thing a target-amount statement must never do. Rows dated ahead of
		// the generating clock are not hypothetical: a log written across hosts
		// only needs one of them stepping its clock forward.
		if !rec.TS.Before(end) {
			continue
		}
		cny, rated := rec.BilledCNY()
		if !rated {
			cny = rec.BilledOrCost() * fallbackRate
		}
		achievedCNY += cny
		start = rec.TS
		if achievedCNY >= targetCNY {
			return start, end, achievedCNY, nil
		}
	}
	return time.Time{}, time.Time{}, achievedCNY, errStatementTargetUnreachable
}

// statementRange resolves the inclusive day labels into the half-open instant
// window [start, end) that rows are compared against.
//
// The labels are interpreted in loc, the display zone, because that is the zone
// the request log buckets days in — reading them as UTC would shift every
// boundary by the offset and silently move requests between statements.
func statementRange(from, to string, loc *time.Location) (fromDay, toDay string, start, end time.Time, err error) {
	const layout = "2006-01-02"
	today := time.Now().In(loc)

	parse := func(s, field string) (time.Time, error) {
		s = strings.TrimSpace(s)
		if s == "" {
			return time.Time{}, nil
		}
		d, perr := time.ParseInLocation(layout, s, loc)
		if perr != nil {
			return time.Time{}, fmt.Errorf("%s must be YYYY-MM-DD", field)
		}
		return d, nil
	}

	f, err := parse(from, "from")
	if err != nil {
		return "", "", time.Time{}, time.Time{}, err
	}
	t, err := parse(to, "to")
	if err != nil {
		return "", "", time.Time{}, time.Time{}, err
	}

	if t.IsZero() {
		t = time.Date(today.Year(), today.Month(), today.Day(), 0, 0, 0, 0, loc)
	}
	if f.IsZero() {
		f = t.AddDate(0, 0, -(statementDefaultDays - 1))
	}
	if t.Before(f) {
		f, t = t, f
	}
	if days := int(t.Sub(f).Hours()/24) + 1; days > statementMaxRangeDays {
		return "", "", time.Time{}, time.Time{},
			fmt.Errorf("range too wide: %d days (max %d)", days, statementMaxRangeDays)
	}

	// end is exclusive at the start of the day after `to`, which is what makes
	// the range include everything that happened on `to` itself.
	return f.Format(layout), t.Format(layout), f, t.AddDate(0, 0, 1), nil
}
