// Package statement renders a per-token usage statement — the itemised record
// of what a client token actually spent over a date range, as a PDF.
//
// Every amount traces to a request-log row: the charge the wallet was debited
// (requestlog.Record.BilledOrCost) converted at the USD→CNY rate that row was
// settled at (Record.CNYPerUSD). Because the rate is a per-row historical fact
// rather than a display-time lookup, the same range exported months apart
// totals identically, and no figure on the page depends on what the market is
// doing when you print it. That is the whole reason the rate is stored.
//
// The document is denominated in CNY only. Users pay in CNY and read their
// balance in CNY; the USD the ledger happens to use internally is an
// implementation detail and printing it just invites the question of which
// number is real.
//
// A statement can also be generated by target amount instead of by date
// range (Statement.ByTarget / TargetCNY): the caller names a yuan figure and
// the server walks backward from the most recent request until the running
// total reaches it, then renders whatever [start, now) window that turned
// out to be. Two things keep that from being "a total dialled to whatever
// someone needs":
//
//   - The range that produced the figure is printed on the document, in the
//     same place and the same font as an ordinary date-range statement's
//     range — never hidden, never presented as if the caller had picked
//     those dates on purpose.
//   - The target itself is capped, server-side, at the account's real
//     Alipay-paid total. A target above that would let someone manufacture
//     a bigger "consumption" figure than they ever paid for; the cap makes
//     the document at most a receipt for money that changed hands.
//
// If the account's entire retained log doesn't add up to the requested
// target even once every row is counted, the statement is refused outright
// rather than rendered short — a document captioned "target ¥500" that only
// covers ¥300 of real spend is exactly the misleading artifact this feature
// has to avoid producing.
package statement

import (
	"sort"
	"time"
)

// MaxDetailLines caps the itemised section. A token doing sustained traffic
// can log six figures of requests in a month, and a PDF is a poor database:
// past a few thousand rows the file is slow to open, painful to scroll, and
// nobody reads it. When the cap bites, the summary totals still cover every
// request in the range — only the listing is a prefix, and the document says
// so rather than quietly appearing complete.
const MaxDetailLines = 3000

// Line is one billable request.
type Line struct {
	TS          time.Time
	Provider    string
	Model       string
	Input       int64
	Output      int64
	CacheRead   int64
	CacheCreate int64
	// BilledCNY is what this request cost, in yuan, at its own settle-time
	// rate. Zero on requests that failed before settling.
	BilledCNY float64
	// RateWasStored is false when the row predates per-row rate capture and
	// BilledCNY had to be derived at the deployment's current rate. Counted,
	// not shown per row — see Statement.UnratedRequests.
	RateWasStored bool
	Status        int
}

// ModelRow is the per-model rollup printed above the itemised lines.
type ModelRow struct {
	Model     string
	Requests  int64
	BilledCNY float64
}

// Statement is everything the renderer needs. Fill it via Observe + Rollup.
type Statement struct {
	// Identity of the holder. TokenMasked is the same mask the request log
	// stores; the full token never appears here, so a statement is safe to
	// hand to somebody else.
	TokenMasked string
	TokenName   string
	Group       string

	// Range, as inclusive day labels in the deployment's display timezone.
	FromDay string
	ToDay   string
	// TZName is the zone those labels are in. Printed because "2026-08-15"
	// covers a different set of requests in Shanghai than in UTC, and a reader
	// reconciling against another system needs to know which was meant.
	TZName      string
	GeneratedAt time.Time

	// ByTarget is true when FromDay/ToDay were derived by scanning backward
	// from the newest request until spend reached TargetCNY, rather than
	// named by the caller. The renderer must caption the range differently in
	// this mode — a target-derived window that prints identically to an
	// ordinary date range would misrepresent how it was chosen.
	ByTarget bool
	// TargetCNY is the requested figure that produced FromDay/ToDay when
	// ByTarget is set. Zero (and unused) otherwise.
	TargetCNY float64
	// RangeStart/RangeEnd are the exact instants a target-derived window spans,
	// set only when ByTarget. The window starts at the timestamp of the one
	// request that carried the running total up to the target, which is some
	// moment in the middle of a day — so printing only FromDay would claim the
	// statement covers all of that day when it covers part of it. A document
	// offered as evidence has to state the boundary it actually used.
	RangeStart time.Time
	RangeEnd   time.Time
	// TotalPaidCNY is the token's total Alipay-paid CNY, independent of this
	// statement's range — the ceiling a target request is checked against
	// before the range is even computed. Zero when SaaS billing is disabled.
	// Not printed on the PDF; carried through only so the JSON preview can
	// show the ceiling without a second round trip.
	TotalPaidCNY float64

	// Range totals. Requests counts every request in range, including those
	// dropped from Lines by MaxDetailLines.
	Requests  int64
	BilledCNY float64

	// Running totals for this token across the whole retained request log.
	//
	// LifetimeDays is the retention window those totals actually cover, and is
	// printed beside them: calling a 90-day figure "累计" invites a reader to
	// treat it as all-time, which it only is for a token younger than
	// retention. Both windows come from the same scan, so they are directly
	// comparable.
	LifetimeRequests  int64
	LifetimeBilledCNY float64
	LifetimeDays      int

	// UnitemisedCNY is spend the wallet was really debited over this range that
	// no request-log row accounts for.
	//
	// The debit and the itemised row are written by different code on different
	// paths, so the log can lose a line the ledger still holds — a crash, a disk
	// problem, a retention prune. A statement built from the log alone then
	// under-reports what the customer actually paid, which is the one direction
	// a spend record must never be wrong in. Carrying the difference as its own
	// labelled line makes the document total match the money without inventing
	// the requests behind it.
	//
	// Zero when the two agree, when billing is off, or when the log accounts for
	// more than the ledger — an overage is not evidence of a missing charge and
	// is never shown as one.
	UnitemisedCNY float64
	// ChargedCNY is the ledger's own total for the range: BilledCNY plus
	// UnitemisedCNY. Zero when no ledger figure was available, in which case the
	// renderer omits the reconciliation entirely rather than implying the
	// itemised total was checked against anything.
	ChargedCNY float64

	// UnratedRequests counts in-range rows written before per-row rate capture
	// existed, whose yuan amount had to be derived at the current rate instead
	// of their own. Non-zero only during the retention window following that
	// rollout; the renderer footnotes it while it lasts and says nothing once
	// it reaches zero, rather than carrying a permanent caveat for a
	// transitional condition.
	UnratedRequests int64

	// ByModel is finalised by Rollup from the Observe tally. It covers every
	// request in the range, not just the ones retained in Lines, so it sums to
	// BilledCNY and agrees with both the summary block and the closing total.
	ByModel []ModelRow
	// byModel accumulates that tally. Unexported so the only way to fill it is
	// Observe, which every in-range row goes through.
	byModel map[string]*ModelRow

	Lines []Line
	// LinesTruncated reports that Lines is a prefix of the range rather than
	// all of it. The renderer discloses this on the page when set.
	LinesTruncated bool
}

// Observe tallies one in-range request into the range totals and the per-model
// rollup.
//
// Callers must call it for every request in the range — including the ones
// MaxDetailLines drops from Lines, and including the preview path that keeps no
// lines at all. Deriving the table from Lines instead (as this did) left the
// preview's rollup empty and, on a truncated statement, printed a per-model
// table that summed to less than the total directly beneath it.
func (s *Statement) Observe(model string, billedCNY float64, rateWasStored bool) {
	s.Requests++
	s.BilledCNY += billedCNY
	if !rateWasStored {
		s.UnratedRequests++
	}
	if s.byModel == nil {
		s.byModel = make(map[string]*ModelRow)
	}
	m := model
	if m == "" {
		m = "(unknown)"
	}
	r, ok := s.byModel[m]
	if !ok {
		r = &ModelRow{Model: m}
		s.byModel[m] = r
	}
	r.Requests++
	r.BilledCNY += billedCNY
}

// Rollup finalises ByModel from the Observe tally, sorted by spend descending
// so the models that dominate the bill lead the table.
func (s *Statement) Rollup() {
	rows := make([]ModelRow, 0, len(s.byModel))
	for _, r := range s.byModel {
		rows = append(rows, *r)
	}
	sort.Slice(rows, func(i, j int) bool {
		if rows[i].BilledCNY != rows[j].BilledCNY {
			return rows[i].BilledCNY > rows[j].BilledCNY
		}
		return rows[i].Model < rows[j].Model
	})
	s.ByModel = rows
}
