// Package statement renders a per-token usage statement — the itemised record
// of what a client token actually spent over a date range, as a PDF.
//
// Every amount traces to a request-log row: the charge the wallet was debited
// (requestlog.Record.BilledOrCost) converted at one USD→CNY rate for the whole
// document (Statement.CNYPerUSD, the deployment's rate at export time). The
// request log carries no per-row rate, so there is nothing historical to
// convert at — which means the same range exported after the market moves
// totals differently. The rate is therefore printed on the page: a reader can
// see which one produced these figures, and reproduce them, rather than being
// left to guess why two copies disagree.
//
// The document is denominated in CNY only. Users pay in CNY and read their
// balance in CNY; the USD the ledger happens to use internally is an
// implementation detail and printing it just invites the question of which
// number is real.
//
// A statement can also be generated by target amount instead of by date
// range (Statement.ByTarget / TargetCNY): the caller names a yuan figure and
// the server walks backward from the most recent request until the running
// total reaches it, then renders whatever [start, now) window that turned
// out to be. Two things keep that from being "a total dialled to whatever
// someone needs":
//
//   - The range that produced the figure is printed on the document, in the
//     same place and the same font as an ordinary date-range statement's
//     range — never hidden, never presented as if the caller had picked
//     those dates on purpose.
//   - Real spend is the only ceiling, and it is a hard one: every line is a
//     charge that really happened, so no amount of asking can conjure a row.
//     (It was briefly also capped at the account's Alipay-paid total. That cap
//     is gone — a wallet funded by operator credit reported a ceiling of zero,
//     so an account could not export a statement of its own consumption.)
//
// If the account's entire retained log doesn't add up to the requested
// target even once every row is counted, the statement is refused outright
// rather than rendered short — a document captioned "target ¥500" that only
// covers ¥300 of real spend is exactly the misleading artifact this feature
// has to avoid producing.
package statement

import (
	"sort"
	"time"
)

// MaxDetailLines caps the itemised section. A token doing sustained traffic
// can log six figures of requests in a month, and a PDF is a poor database:
// past a few thousand rows the file is slow to open, painful to scroll, and
// nobody reads it. When the cap bites, the summary totals still cover every
// request in the range — only the listing is a prefix, and the document says
// so rather than quietly appearing complete.
const MaxDetailLines = 3000

// Line is one billable request.
//
// There is deliberately no cache-write count. OpenAI's usage block has no such
// concept — it reports cached_tokens (a read) and nothing else — and this
// deployment's traffic is overwhelmingly OpenAI, so the column was structurally
// zero rather than merely empty. A column that can never carry a value is worse
// than no column: it reads as "this request wrote no cache" when the truth is
// "the upstream never said".
type Line struct {
	TS        time.Time
	Provider  string
	Model     string
	Input     int64
	Output    int64
	CacheRead int64
	// BilledCNY is what this request cost, in yuan, at Statement.CNYPerUSD.
	// Zero on requests that failed before settling.
	BilledCNY float64
	Status    int
	// Member is the masked client token that made the request. Only a group
	// statement fills it, and only a group statement prints it: on a per-token
	// document every row has the same value, which is already in the header.
	// Without it an itemised group listing is a column of amounts nobody can
	// attribute, which for a shared reimbursement attachment is the one thing
	// the listing is for.
	Member string
}

// ModelRow is the per-model rollup printed above the itemised lines.
type ModelRow struct {
	Model     string
	Requests  int64
	BilledCNY float64
}

// Statement is everything the renderer needs. Fill the range totals via either
// Observe (row by row) or SetRangeTotals (pre-summed), then Rollup.
type Statement struct {
	// Identity of the holder. TokenMasked is the same mask the request log
	// stores; the full token never appears here, so a statement is safe to
	// hand to somebody else.
	TokenMasked string
	TokenName   string
	Group       string

	// Range, as inclusive day labels in the deployment's display timezone.
	FromDay string
	ToDay   string
	// TZName is the zone those labels are in. Printed because "2026-08-15"
	// covers a different set of requests in Shanghai than in UTC, and a reader
	// reconciling against another system needs to know which was meant.
	TZName      string
	GeneratedAt time.Time

	// ByTarget is true when FromDay/ToDay were derived by scanning backward
	// from the newest request until spend reached TargetCNY, rather than
	// named by the caller. The renderer must caption the range differently in
	// this mode — a target-derived window that prints identically to an
	// ordinary date range would misrepresent how it was chosen.
	ByTarget bool
	// TargetCNY is the requested figure that produced FromDay/ToDay when
	// ByTarget is set. Zero (and unused) otherwise.
	TargetCNY float64
	// RangeStart/RangeEnd are the exact instants a target-derived window spans,
	// set only when ByTarget. The window starts at the timestamp of the one
	// request that carried the running total up to the target, which is some
	// moment in the middle of a day — so printing only FromDay would claim the
	// statement covers all of that day when it covers part of it. A document
	// offered as evidence has to state the boundary it actually used.
	RangeStart time.Time
	RangeEnd   time.Time
	// TotalPaidCNY is the token's total Alipay-paid CNY, independent of this
	// statement's range — the ceiling a target request is checked against
	// before the range is even computed. Zero when SaaS billing is disabled.
	// Not printed on the PDF; carried through only so the JSON preview can
	// show the ceiling without a second round trip.
	TotalPaidCNY float64

	// CNYPerUSD is the single rate every yuan figure on this document was
	// converted at. Printed in the identity block: with no per-row rate in the
	// request log there is nothing that pins these figures to the moment they
	// were charged, so the document has to state which rate produced them or a
	// reader comparing two exports of the same range has no way to explain the
	// difference. Never zero — see the fallback chain in internal/admin.
	CNYPerUSD float64

	// Range totals. Requests counts every request in range, including those
	// dropped from Lines by MaxDetailLines.
	Requests  int64
	BilledCNY float64

	// Running totals for this token across the whole retained request log.
	//
	// LifetimeDays is the retention window those totals actually cover, and is
	// printed beside them: calling a 90-day figure "累计" invites a reader to
	// treat it as all-time, which it only is for a token younger than
	// retention. Both windows come from the same scan, so they are directly
	// comparable.
	LifetimeRequests  int64
	LifetimeBilledCNY float64
	LifetimeDays      int

	// UnitemisedCNY is spend the wallet was really debited over this range that
	// no request-log row accounts for.
	//
	// The debit and the itemised row are written by different code on different
	// paths, so the log can lose a line the ledger still holds — a crash, a disk
	// problem, a retention prune. A statement built from the log alone then
	// under-reports what the customer actually paid, which is the one direction
	// a spend record must never be wrong in. Carrying the difference as its own
	// labelled line makes the document total match the money without inventing
	// the requests behind it.
	//
	// Zero when the two agree, when billing is off, or when the log accounts for
	// more than the ledger — an overage is not evidence of a missing charge and
	// is never shown as one.
	UnitemisedCNY float64
	// ChargedCNY is the ledger's own total for the range: BilledCNY plus
	// UnitemisedCNY. Zero when no ledger figure was available, in which case the
	// renderer omits the reconciliation entirely rather than implying the
	// itemised total was checked against anything.
	ChargedCNY float64

	// ByModel is finalised by Rollup from the tally below. It covers every
	// request in the range, not just the ones retained in Lines, so it sums to
	// BilledCNY and agrees with both the summary block and the closing total.
	ByModel []ModelRow
	// byModel accumulates that tally. Unexported so the only ways to fill it
	// are Observe, which every in-range row goes through, and SetRangeTotals,
	// which replaces it wholesale from a pre-summed source.
	byModel map[string]*ModelRow

	Lines []Line
	// LinesTruncated reports that Lines is a prefix of the range rather than
	// all of it. The renderer discloses this on the page when set.
	LinesTruncated bool
	// HasTokenDetail is set by Rollup: true when at least one retained Line
	// carries a nonzero token count. Rows written before 2026-08-09 have no
	// token counts at all — the numbers never existed at the source and cannot
	// be recovered — so an old range would otherwise print three columns of
	// zeroes. The renderer drops those columns entirely instead, because a
	// table of zeroes claims the requests consumed nothing.
	HasTokenDetail bool
}

// There are exactly two ways to fill the range totals and the per-model table,
// and a caller picks one:
//
//   - Observe, once per in-range row, when the caller is walking rows anyway.
//   - SetRangeTotals, when the same figures are already available pre-summed
//     and no row needs to be materialised to get them.
//
// They are alternatives, never a pair: SetRangeTotals replaces the tally rather
// than adding to it, so a caller that reaches for both cannot double-count —
// the last call simply wins.

// Observe tallies one in-range request into the range totals and the per-model
// rollup.
//
// Callers on this path must call it for every request in the range — including
// the ones MaxDetailLines drops from Lines, and including the preview path that
// keeps no lines at all. Deriving the table from Lines instead (as this did)
// left the preview's rollup empty and, on a truncated statement, printed a
// per-model table that summed to less than the total directly beneath it.
func (s *Statement) Observe(model string, billedCNY float64) {
	s.Requests++
	s.BilledCNY += billedCNY
	if s.byModel == nil {
		s.byModel = make(map[string]*ModelRow)
	}
	m := model
	if m == "" {
		m = "(unknown)"
	}
	r, ok := s.byModel[m]
	if !ok {
		r = &ModelRow{Model: m}
		s.byModel[m] = r
	}
	r.Requests++
	r.BilledCNY += billedCNY
}

// SetRangeTotals fills the range totals and the per-model tally from figures
// that were already summed elsewhere — a pre-aggregated query, in the caller
// that has one — so a statement over a hundred thousand requests costs no more
// than a statement over ten.
//
// It replaces whatever was tallied before rather than adding to it. Observe and
// this are two ways of computing the same three things, so the failure mode
// worth designing out is a caller that runs both and prints double; overwriting
// makes that impossible without an error path a request handler would have to
// decide what to do with.
//
// byModel must cover the whole range, and its BilledCNY must sum to billedCNY,
// for the same reason Observe must see every row: the table sits directly above
// the total and a reader adds it up.
//
// Rollup still has to be called afterwards — it is what sorts the table and
// decides whether the itemised section has token columns.
func (s *Statement) SetRangeTotals(requests int64, billedCNY float64, byModel []ModelRow) {
	s.Requests = requests
	s.BilledCNY = billedCNY
	s.byModel = make(map[string]*ModelRow, len(byModel))
	for _, r := range byModel {
		row := r
		if row.Model == "" {
			row.Model = "(unknown)"
		}
		if prev, ok := s.byModel[row.Model]; ok {
			// Defensive: two input rows naming one model would otherwise leave
			// the table summing to less than the total printed beneath it.
			prev.Requests += row.Requests
			prev.BilledCNY += row.BilledCNY
			continue
		}
		s.byModel[row.Model] = &row
	}
}

// Rollup finalises ByModel from whichever tally filled it — Observe's or
// SetRangeTotals' — sorted by spend descending
// so the models that dominate the bill lead the table, and decides whether the
// itemised section has token counts worth a column at all.
//
// It must be called after Lines is filled — HasTokenDetail is read off the rows
// that will actually be printed, not off the range totals, since those are the
// only numbers the columns would show.
func (s *Statement) Rollup() {
	s.HasTokenDetail = false
	for _, ln := range s.Lines {
		if ln.Input != 0 || ln.Output != 0 || ln.CacheRead != 0 {
			s.HasTokenDetail = true
			break
		}
	}

	rows := make([]ModelRow, 0, len(s.byModel))
	for _, r := range s.byModel {
		rows = append(rows, *r)
	}
	sort.Slice(rows, func(i, j int) bool {
		if rows[i].BilledCNY != rows[j].BilledCNY {
			return rows[i].BilledCNY > rows[j].BilledCNY
		}
		return rows[i].Model < rows[j].Model
	})
	s.ByModel = rows
}
